### ISSUE TITLE
How does jill choose "PlanVariables"

### ISSUE THREAD

**Issue by mostafamohajeri** [agentsoz/jill#7]
Hi,

I am trying to work with jill, I had a question, how is selecting a plan relate to selecting variables to that plan,

Consider I have 2 plans to go to park
Walk and Taxi
and I have 5 parks, So the function for a random selection (Or first,last), the algorithm should choose 1- a plan by random and 2- a tuple from its bindings randomly. Is this function really doing this?

```
private Plan selectPlanAtRandom() {
        Plan plan = null;
        Set<Belief> vars = null;
        int index = rand.nextInt(size());
        int idx = 0;
        boolean bindingsExist = false;
        for (Plan p : bindings.keySet()) {
            vars = bindings.get(p);
            bindingsExist = (vars != null && !vars.isEmpty());
            idx += bindingsExist ? vars.size() : 1;
            if (idx > index) {
                plan = p;
                if (bindingsExist) {
                    index = index - (idx - vars.size());
                    setPlanVariables(plan.getAgent(), plan, vars, index);
                }
                break;
            }
        }
        return plan;
    }
```

I think the relation between Plans index and Bindings index is lost here.

Thanks

**Comment by dhixsingh** [comment]
Thanks for the question @mostafamohajeri. Yes it is meant to work as you mentioned. 

So in your example, if the context of all the plans is true, then `bindings={Walk(Park1), ..., Walk(Park5), Taxi(Park1), ..., Taxi(Park5)}`, i.e., a list of size 10; and if you rolled a 5 say, then it will pick the sixth element in the list, i.e., `Taxi(Park1)`, giving `plan=Taxi, var=Park1`.

If you are seeing something different, then would you mind creating a simple test to show the problem? I can't say it is heavily tested, although some tests exist in [PlanBindingsTest.java](https://github.com/agentsoz/jill/blob/06f7e416b9e2677d51bdbd82a073ffd6623293e7/jill/src/test/java/io/github/agentsoz/jill/lang/PlanBindingsTest.java).

**Comment by mostafamohajeri** [comment]
So with this algorithm you are assuming the probability of selecting a plan by the number of variables it has. maybe this was the case in your design?
So if I have the goal of `HavingFun`, and I have the plans of `{Park,Cinema}` and my belief base is `{park1,park2,park3,...,park99},{cinema1}` I will have the `bindings = {Park(park1),Park(park2), ... Park(park99), Cinema(cinema1)}` which means probability of choosing the plan Park is implicitly 0.99 just because there are more parks around?

Am I right? Can I ask if this was your original intent?

**Comment by dhixsingh** [comment]
Yes correct, that is how it is intended to be.  

The infrastructure can’t put any meaning to the options—parks and cinemas are just labels, they only hold meaning for the user. They are treated equally for plan selection. 

If you wish to treat them differently, for instance, say for some reason you would like a rule that states “if `park37` is available then always select it”, or “give equal weighting to plan types, irrespective of the number of options/bindings for each” then you would want to put this in meta-level reasoning where you can reason over your available options. See for example:

https://github.com/agentsoz/jill/blob/06f7e416b9e2677d51bdbd82a073ffd6623293e7/jill/src/test/java/io/github/agentsoz/jill/testgreeter/TestGreeterAgent.java#L160

**Comment by mostafamohajeri** [comment]
Thanks for clarifying, It makes sense now.

I think the Symbolic AI community needs to put more focus on meta-planning to make it more well-defined, meta-planning should already move from "being an extension" and become a defined part of BDI architecture. With the bulk of research on adding some sort of meta-planning to BDI (including yours), I think it should not be an extension anymore.
