### ISSUE TITLE
Event system/Reactive bahavior/Plan failure

### ISSUE THREAD

**Issue by mostafamohajeri** [agentsoz/jill#8]
Hi,

Does Jill have these features at this point? If not, Do you plan to add them?

1- Events and Reactive behavior of agents,new beliefs that can fire new goals or plans.
2- Plan failure recovery and back propagation.

Thanks

**Comment by mostafamohajeri** [comment]
Oh now I saw the plan failure Issue #2

**Comment by dhixsingh** [comment]
Yes failure recovery is planned and #2 is related to that.

There is no plan to implement anything specific for (1) at this stage. For the most part this is possible by explicitly posting a goal to trigger a reaction to external events and/or internal belief changes.
